version: '3'

services:
  website:
    container_name: my-ufo
    image: 'chanasia/myufo:latest'
    ports:
      - 3001:3000
    environment:
     - HOSTNAME=chanasia.xyz
    restart: 'unless-stopped'
